version: '3.1'

services:

  dot-api:
    image: dot-api
    container_name: dot-api
    restart: always
    build:
      context: .
      dockerfile: Dot.Api/Dockerfile
      no_cache: true
    depends_on:
      - ollama
      - mongo
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      MongoDbSettings__ConnectionString: "mongodb://${DOT_USER_NAME}:${DOT_PASS}@mongo:27017/dot?authSource=dot"
      MongoDbSettings__DatabaseName: "dot"
      RabbitMQSettings__Exchange: "dot_topic"
      RabbitMQSettings__HostName: "rabbitmq"
      RabbitMQSettings__UserName: ${DOT_USER_NAME}
      RabbitMQSettings__Password: ${DOT_PASS}
      OllamaOptions__Url: "http://ollama:11434"
      OllamaOptions__DefaultModel: "openhermes"
    ports:
      - "8080:8080"

  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    container_name: ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama

  mongo:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db 
      - mongo_config:/data/configdb

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBIT_CONTAINER_NAME}
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${ADMIN_USER_NAME}
      RABBITMQ_DEFAULT_PASS: ${ADMIN_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

#  dot-speech-tts:
#    build:
#      context: ./dot_speech_tts
#      dockerfile: Dockerfile
#      no_cache: true
#    environment:
#      RABBITMQ_HOST: rabbitmq
#      TTS_INPUT_QUEUE: dot.speech.tts
#      TTS_OUTPUT_QUEUE: dot.speech.tts.response
#      SHARED_VOLUME_PATH: /shared/audio
#    volumes:
#      - dot_speech:/output

volumes:
  ollama_models:
  mongo_data:
  mongo_config:
  rabbitmq_data:
  #dot_speech:
