version: '3.1'

services:

  mongo:
    image: mongo
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USER_NAME}
      MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASS}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db 
      - mongo_config:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: dot-mongo-ui
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USER_NAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${ADMIN_USER_NAME}:${ADMIN_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    volumes:
      - mongo_express_data:/data/db 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ${RABBIT_CONTAINER_NAME}
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${ADMIN_USER_NAME}
      RABBITMQ_DEFAULT_PASS: ${ADMIN_PASS}
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
      
volumes:
  mongo_data:
  mongo_config:
  mongo_express_data:
  rabbitmq_data: