version: '3.1'

services:

  mongo:
    image: mongo
    container_name: dot-mongo-db
    restart: always
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db 
      - mongo_config:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: dot-mongo-ui
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASS}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    volumes:
      - mongo_express_data:/data/db 
      
volumes:
  mongo_data:
  mongo_config:
  mongo_express_data: